# Site settings
baseurl = "http://geertvd.github.io/"
languageCode = "en-us"
title = "Geert van Dort"
theme = "hugo-cactus-theme"
# Enter your tracking code to enable Google Analytics
googleAnalytics = ""
# Disable comments by leaving disqusShortname empty
disqusShortname = ""

[params]
	name = "Geert van Dort"
	#description = ""
	bio = "Freelancer - Programmer - Drupalista"
	# Enter optionally your twitter account
	twitter = "https://www.twitter.com/geertvd"
	enableRSS = false

	# The variables below are optionally too and can be used to
	# translate or customize each string of the theme.

	# Navigation links
	home = ""
	about = ""
	subscribe = ""
	# Pagination links
	olderPosts = ""
	newerPosts = ""
	readMore = ""
	copyright = ""
	# Sharing options and author information in posts
	aboutAuthor = ""
	tweet = ""
	share = ""
	# 404 page
	title404 = ""
	subtitle404 = ""

    # Social icons style - circle, rounded, or empty
    socialIconStyle = "circle"

# Add additional social link entries underneath
[social]
    twitter = "https://www.twitter.com/geertvd"
    drupal = "https://www.drupal.org/u/geertvd"
    github = "https://www.github.com/geertvd"
    linkedin = "https://be.linkedin.com/in/geertvandort"

